In [75]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [76]:
import warnings
warnings.filterwarnings('ignore')

In [77]:
import os

print(os.path.getsize('label_encoder_gender.pkl'))

259

In [78]:
model = load_model('model.h5')


with open('one_hot_encoder_geography.pkl', 'rb') as file:
    one_hot_encoder_geography = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [79]:
input_data = {
    'CreditScore': 600,
    'Geography':'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000,
}

In [88]:
input_data_df = pd.DataFrame([input_data])
gender_encoder = label_encoder_gender.transform([[input_data['Gender']]])
input_data_df['Gender'] = pd.DataFrame(gender_encoder,columns = ['Gender'])
geo_encoder = one_hot_encoder_geography.transform([[input_data['Geography']]]).toarray()
geo_encoder_df = pd.DataFrame(geo_encoder,columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))
geo_encoder_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [91]:
df = pd.concat([input_data_df.drop('Geography',axis=1), geo_encoder_df],axis = 1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [97]:
scaler_df = scaler.transform(df)

In [99]:
y_pred = model.predict(scaler_df)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

array([[0.06111062]], dtype=float32)

In [100]:
pred_pro = y_pred[0][0]

In [102]:
if  pred_pro >= 0.5:
    print("The Customer is likely to churn.")
else:
    print('TheCustomer is not likely to churn.')

TheCustomer is not likely to churn.