In [111]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle
import tensorflow as tf
import datetime

In [112]:
df = pd.read_csv('E:\projects\Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [113]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [114]:
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [115]:
one_hot_encoder = OneHotEncoder()
encoder = one_hot_encoder.fit_transform(df[['Geography']]).toarray()

In [116]:
geography_df = pd.DataFrame(encoder, columns=one_hot_encoder.get_feature_names_out())

In [117]:
df = pd.concat([df,geography_df],axis=1)
df.head()

   CreditScore Geography  ...  Geography_Germany  Geography_Spain
0          619    France  ...                0.0              0.0
1          608     Spain  ...                0.0              1.0
2          502    France  ...                0.0              0.0
3          699    France  ...                0.0              0.0
4          850     Spain  ...                0.0              1.0

[5 rows x 14 columns]

In [118]:
df = df.drop('Geography',axis=1)

In [119]:
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [120]:
x = df.drop('EstimatedSalary',axis=1)
y = df['EstimatedSalary']

In [121]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [122]:
scaler = StandardScaler()
scaler.fit_transform(x_train)
scaler.transform(x_test)

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [123]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder,file)

with open('one hot encoder Geography.pkl','wb') as file:
    pickle.dump(one_hot_encoder,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [124]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [125]:
model = Sequential([Dense(64,activation='relu',input_shape = (x_train.shape[1],)),
                    Dense(32,activation='relu'),
                    Dense(1)
                ])

e:\ml projecr\venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [126]:
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [127]:
model.compile(optimizer=opt, loss= loss,metrics=['accuracy'])

In [128]:
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir = 'regression/log/fit' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensor_flow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [129]:
early_stopping_callback = EarlyStopping(patience=5,monitor='val_loss',restore_best_weights=True)

In [130]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=50,callbacks=[tensor_flow_callback,early_stopping_callback])

Epoch 1/50

250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0000e+00 - loss: 1618761.5000 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 1618761.1250 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 1618761.7500 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 1618761.2500 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 1618760.5000 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 1618761.3750 - val_accuracy: 0.0000e+00 - val_loss: 1591275.6250

In [131]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.